name: Debian Package Build

on:
  push:
    branches:
      - 'main'

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Build matrix
        id: set-matrix
        run: |
          git_tmp_dir=$(mktemp -d /tmp/distro-info-data-XXXXX)
          git clone --depth 1 https://salsa.debian.org/debian/distro-info-data "${git_tmp_dir}"

          releases=()

          for release in $(awk -F ',' -v today="$(date --utc "+%F")" \
              'BEGIN {OFS=","} NR>1 { if (($6 == "" || $6 >= today) && ($5 != "" && $5 <= today)) print $3 }' \
              "${git_tmp_dir}/ubuntu.csv"); do
              releases+=("ubuntu:${release}")
          done

          for release in $(awk -F ',' -v today="$(date --utc "+%F")" \
              'BEGIN {OFS=","} NR>1 { if (($6 == "" || $6 >= today) && ($4 != "" && $4 <= today)) print $3 }' \
              "${git_tmp_dir}/debian.csv" | grep -v -E "(sid|experimental)"); do
              releases+=("debian:${release}")
          done

          matrix=$(printf "%s\n" "${releases[@]}" | jq -nRc '[inputs]')

          echo "::set-output name=matrix::${matrix}"

  build-standalone-package:
    runs-on: ubuntu-latest
    needs: build-matrix
    container:
      image: ${{ matrix.target }}
    strategy:
      matrix:
        arch:
          - amd64
        target: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
        package:
          - rdma-core
          - libbpf
      max-parallel: 5
    env:
        BUILD_TARGET: ${{ matrix.target }}
        BUILD_ARCH: ${{ matrix.arch }}
        BUILD_PACKAGE: ${{ matrix.package }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y upgrade
          apt-get -y install git devscripts dpkg-dev debhelper equivs debian-keyring ubuntu-keyring
      - name: Backport build tools on xenial
        run: |
          apt-get update
          apt-get install -y -t xenial-backports debhelper ninja-build
        if: matrix.target == 'ubuntu:xenial'
      - name: Build package
        run: |
          cd "./${{ matrix.package }}/"
          ./boot.sh
          cd src
          mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
          dpkg-buildpackage -b -us -uc -rfakeroot -j4
          dirname=$(echo ${{ matrix.target }} | tr ':' '_')
          package_path="${GITHUB_WORKSPACE}/packages/${dirname}"
          mkdir -p "${package_path}"
          mv ../*.deb "${package_path}"
      - name: Publish packages to cloudsmith
        uses: wanduow/action-cloudsmith-upload-packages@v1.1
        with:
          path: packages/
          repo: wand/openvswitch
          username: brad-cowie
          api_key: ${{ secrets.CLOUDSMITH_API_KEY }}
