name: Debian Package Build

on:
  push:
    branches:
      - 'main'

jobs:
  build-rdma-core:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.target }}
    strategy:
      matrix:
        arch:
          - amd64
        target:
            - "debian:stretch"
            - "debian:buster"
            - "ubuntu:xenial"
            - "ubuntu:bionic"
            - "ubuntu:focal"
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get -y upgrade
          apt-get -y install git devscripts dpkg-dev debhelper equivs
      - name: Build package
        run: |
          mkdir rdma-core
          cd rdma-core
          git clone --recurse-submodules https://github.com/linux-rdma/rdma-core -b v32.0 src
          cd src
          mk-build-deps -i -r -t 'apt-get -f -y --force-yes'
          dpkg-buildpackage -b -us -uc -rfakeroot -j4
      - name: Store packages
        run: |
          dirname=$(echo ${{ matrix.target }} | tr ':' '_')
          cd rdma-core
          mkdir -p packages/${dirname}
          cp *.deb packages/${dirname}/
      - name: Publish packages to cloudsmith
        uses: wanduow/action-cloudsmith-upload-packages@v1
        with:
          path: packages/
          repo: wand/openvswitch
          username: brad-cowie
          api_key: ${{ secrets.CLOUDSMITH_API_KEY }}
